<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5oHIghB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5oHIghB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5oHIghB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5oHIghB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5oHIghB\App_KernelDevDebugContainer([
    'container.build_hash' => '5oHIghB',
    'container.build_id' => '852e5c7e',
    'container.build_time' => 1745528507,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container5oHIghB');
