<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYlRNDgy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYlRNDgy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYlRNDgy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYlRNDgy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYlRNDgy\App_KernelDevDebugContainer([
    'container.build_hash' => 'YlRNDgy',
    'container.build_id' => '07bc2251',
    'container.build_time' => 1744871709,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYlRNDgy');
