<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNyvzOtY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNyvzOtY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNyvzOtY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNyvzOtY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNyvzOtY\App_KernelDevDebugContainer([
    'container.build_hash' => 'NyvzOtY',
    'container.build_id' => '93cda112',
    'container.build_time' => 1744289867,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNyvzOtY');
